// <auto-generated />
using System;
using Albiflora.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Albiflora.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Albiflora.API.Entities.Flower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OptimalTemperature")
                        .HasColumnType("double precision");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("ShelfLifeDays")
                        .HasColumnType("integer");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<string>("Variety")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Flowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Красный",
                            Name = "Роза Эквадор",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_1.jpg",
                            ShelfLifeDays = 7,
                            ShopId = 2,
                            Variety = "Эквадор"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Нежно-розовый",
                            Name = "Роза Пионовидная",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_2.jpg",
                            ShelfLifeDays = 6,
                            ShopId = 1,
                            Variety = "Пионовидная"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Розовый",
                            Name = "Пион Сара Бернар",
                            OptimalTemperature = 3.5,
                            PhotoUrl = "flower_3.jpg",
                            ShelfLifeDays = 5,
                            ShopId = 2,
                            Variety = "Сара Бернар"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Белый",
                            Name = "Хризантема Антонов",
                            OptimalTemperature = 5.0,
                            PhotoUrl = "flower_4.jpg",
                            ShelfLifeDays = 14,
                            ShopId = 1,
                            Variety = "Антонов"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Желтый",
                            Name = "Тюльпан Стронг Голд",
                            OptimalTemperature = 2.0,
                            PhotoUrl = "flower_5.jpg",
                            ShelfLifeDays = 6,
                            ShopId = 2,
                            Variety = "Стронг Голд"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Голубой",
                            Name = "Гортензия Магическая",
                            OptimalTemperature = 6.0,
                            PhotoUrl = "flower_6.jpg",
                            ShelfLifeDays = 4,
                            ShopId = 1,
                            Variety = "Магическая"
                        },
                        new
                        {
                            Id = 7,
                            Color = "Фиолетовый",
                            Name = "Эустома Алиса",
                            OptimalTemperature = 4.5,
                            PhotoUrl = "flower_7.jpg",
                            ShelfLifeDays = 10,
                            ShopId = 2,
                            Variety = "Алиса"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Белый",
                            Name = "Альстромерия Вирджиния",
                            OptimalTemperature = 5.0,
                            PhotoUrl = "flower_8.jpg",
                            ShelfLifeDays = 12,
                            ShopId = 1,
                            Variety = "Вирджиния"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Персиковый",
                            Name = "Гвоздика Сортовая",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_9.jpg",
                            ShelfLifeDays = 15,
                            ShopId = 2,
                            Variety = "Сортовая"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Радужный",
                            Name = "Гипсофила Мираж",
                            OptimalTemperature = 7.0,
                            PhotoUrl = "flower_10.jpg",
                            ShelfLifeDays = 20,
                            ShopId = 1,
                            Variety = "Мираж"
                        },
                        new
                        {
                            Id = 11,
                            Color = "Красный",
                            Name = "Роза Эквадор",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_11.jpg",
                            ShelfLifeDays = 7,
                            ShopId = 2,
                            Variety = "Эквадор"
                        },
                        new
                        {
                            Id = 12,
                            Color = "Нежно-розовый",
                            Name = "Роза Пионовидная",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_12.jpg",
                            ShelfLifeDays = 6,
                            ShopId = 1,
                            Variety = "Пионовидная"
                        },
                        new
                        {
                            Id = 13,
                            Color = "Розовый",
                            Name = "Пион Сара Бернар",
                            OptimalTemperature = 3.5,
                            PhotoUrl = "flower_13.jpg",
                            ShelfLifeDays = 5,
                            ShopId = 2,
                            Variety = "Сара Бернар"
                        },
                        new
                        {
                            Id = 14,
                            Color = "Белый",
                            Name = "Хризантема Антонов",
                            OptimalTemperature = 5.0,
                            PhotoUrl = "flower_14.jpg",
                            ShelfLifeDays = 14,
                            ShopId = 1,
                            Variety = "Антонов"
                        },
                        new
                        {
                            Id = 15,
                            Color = "Желтый",
                            Name = "Тюльпан Стронг Голд",
                            OptimalTemperature = 2.0,
                            PhotoUrl = "flower_15.jpg",
                            ShelfLifeDays = 6,
                            ShopId = 2,
                            Variety = "Стронг Голд"
                        },
                        new
                        {
                            Id = 16,
                            Color = "Голубой",
                            Name = "Гортензия Магическая",
                            OptimalTemperature = 6.0,
                            PhotoUrl = "flower_16.jpg",
                            ShelfLifeDays = 4,
                            ShopId = 1,
                            Variety = "Магическая"
                        },
                        new
                        {
                            Id = 17,
                            Color = "Фиолетовый",
                            Name = "Эустома Алиса",
                            OptimalTemperature = 4.5,
                            PhotoUrl = "flower_17.jpg",
                            ShelfLifeDays = 10,
                            ShopId = 2,
                            Variety = "Алиса"
                        },
                        new
                        {
                            Id = 18,
                            Color = "Белый",
                            Name = "Альстромерия Вирджиния",
                            OptimalTemperature = 5.0,
                            PhotoUrl = "flower_18.jpg",
                            ShelfLifeDays = 12,
                            ShopId = 1,
                            Variety = "Вирджиния"
                        },
                        new
                        {
                            Id = 19,
                            Color = "Персиковый",
                            Name = "Гвоздика Сортовая",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_19.jpg",
                            ShelfLifeDays = 15,
                            ShopId = 2,
                            Variety = "Сортовая"
                        },
                        new
                        {
                            Id = 20,
                            Color = "Радужный",
                            Name = "Гипсофила Мираж",
                            OptimalTemperature = 7.0,
                            PhotoUrl = "flower_20.jpg",
                            ShelfLifeDays = 20,
                            ShopId = 1,
                            Variety = "Мираж"
                        },
                        new
                        {
                            Id = 21,
                            Color = "Красный",
                            Name = "Роза Эквадор",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_21.jpg",
                            ShelfLifeDays = 7,
                            ShopId = 2,
                            Variety = "Эквадор"
                        },
                        new
                        {
                            Id = 22,
                            Color = "Нежно-розовый",
                            Name = "Роза Пионовидная",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_22.jpg",
                            ShelfLifeDays = 6,
                            ShopId = 1,
                            Variety = "Пионовидная"
                        },
                        new
                        {
                            Id = 23,
                            Color = "Розовый",
                            Name = "Пион Сара Бернар",
                            OptimalTemperature = 3.5,
                            PhotoUrl = "flower_23.jpg",
                            ShelfLifeDays = 5,
                            ShopId = 2,
                            Variety = "Сара Бернар"
                        },
                        new
                        {
                            Id = 24,
                            Color = "Белый",
                            Name = "Хризантема Антонов",
                            OptimalTemperature = 5.0,
                            PhotoUrl = "flower_24.jpg",
                            ShelfLifeDays = 14,
                            ShopId = 1,
                            Variety = "Антонов"
                        },
                        new
                        {
                            Id = 25,
                            Color = "Желтый",
                            Name = "Тюльпан Стронг Голд",
                            OptimalTemperature = 2.0,
                            PhotoUrl = "flower_25.jpg",
                            ShelfLifeDays = 6,
                            ShopId = 2,
                            Variety = "Стронг Голд"
                        },
                        new
                        {
                            Id = 26,
                            Color = "Голубой",
                            Name = "Гортензия Магическая",
                            OptimalTemperature = 6.0,
                            PhotoUrl = "flower_26.jpg",
                            ShelfLifeDays = 4,
                            ShopId = 1,
                            Variety = "Магическая"
                        },
                        new
                        {
                            Id = 27,
                            Color = "Фиолетовый",
                            Name = "Эустома Алиса",
                            OptimalTemperature = 4.5,
                            PhotoUrl = "flower_27.jpg",
                            ShelfLifeDays = 10,
                            ShopId = 2,
                            Variety = "Алиса"
                        },
                        new
                        {
                            Id = 28,
                            Color = "Белый",
                            Name = "Альстромерия Вирджиния",
                            OptimalTemperature = 5.0,
                            PhotoUrl = "flower_28.jpg",
                            ShelfLifeDays = 12,
                            ShopId = 1,
                            Variety = "Вирджиния"
                        },
                        new
                        {
                            Id = 29,
                            Color = "Персиковый",
                            Name = "Гвоздика Сортовая",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_29.jpg",
                            ShelfLifeDays = 15,
                            ShopId = 2,
                            Variety = "Сортовая"
                        },
                        new
                        {
                            Id = 30,
                            Color = "Радужный",
                            Name = "Гипсофила Мираж",
                            OptimalTemperature = 7.0,
                            PhotoUrl = "flower_30.jpg",
                            ShelfLifeDays = 20,
                            ShopId = 1,
                            Variety = "Мираж"
                        },
                        new
                        {
                            Id = 31,
                            Color = "Красный",
                            Name = "Роза Эквадор",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_31.jpg",
                            ShelfLifeDays = 7,
                            ShopId = 2,
                            Variety = "Эквадор"
                        },
                        new
                        {
                            Id = 32,
                            Color = "Нежно-розовый",
                            Name = "Роза Пионовидная",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_32.jpg",
                            ShelfLifeDays = 6,
                            ShopId = 1,
                            Variety = "Пионовидная"
                        },
                        new
                        {
                            Id = 33,
                            Color = "Розовый",
                            Name = "Пион Сара Бернар",
                            OptimalTemperature = 3.5,
                            PhotoUrl = "flower_33.jpg",
                            ShelfLifeDays = 5,
                            ShopId = 2,
                            Variety = "Сара Бернар"
                        },
                        new
                        {
                            Id = 34,
                            Color = "Белый",
                            Name = "Хризантема Антонов",
                            OptimalTemperature = 5.0,
                            PhotoUrl = "flower_34.jpg",
                            ShelfLifeDays = 14,
                            ShopId = 1,
                            Variety = "Антонов"
                        },
                        new
                        {
                            Id = 35,
                            Color = "Желтый",
                            Name = "Тюльпан Стронг Голд",
                            OptimalTemperature = 2.0,
                            PhotoUrl = "flower_35.jpg",
                            ShelfLifeDays = 6,
                            ShopId = 2,
                            Variety = "Стронг Голд"
                        },
                        new
                        {
                            Id = 36,
                            Color = "Голубой",
                            Name = "Гортензия Магическая",
                            OptimalTemperature = 6.0,
                            PhotoUrl = "flower_36.jpg",
                            ShelfLifeDays = 4,
                            ShopId = 1,
                            Variety = "Магическая"
                        },
                        new
                        {
                            Id = 37,
                            Color = "Фиолетовый",
                            Name = "Эустома Алиса",
                            OptimalTemperature = 4.5,
                            PhotoUrl = "flower_37.jpg",
                            ShelfLifeDays = 10,
                            ShopId = 2,
                            Variety = "Алиса"
                        },
                        new
                        {
                            Id = 38,
                            Color = "Белый",
                            Name = "Альстромерия Вирджиния",
                            OptimalTemperature = 5.0,
                            PhotoUrl = "flower_38.jpg",
                            ShelfLifeDays = 12,
                            ShopId = 1,
                            Variety = "Вирджиния"
                        },
                        new
                        {
                            Id = 39,
                            Color = "Персиковый",
                            Name = "Гвоздика Сортовая",
                            OptimalTemperature = 4.0,
                            PhotoUrl = "flower_39.jpg",
                            ShelfLifeDays = 15,
                            ShopId = 2,
                            Variety = "Сортовая"
                        },
                        new
                        {
                            Id = 40,
                            Color = "Радужный",
                            Name = "Гипсофила Мираж",
                            OptimalTemperature = 7.0,
                            PhotoUrl = "flower_40.jpg",
                            ShelfLifeDays = 20,
                            ShopId = 1,
                            Variety = "Мираж"
                        },
                        new
                        {
                            Id = 41,
                            Color = "Прозрачный",
                            Name = "Матовая пленка",
                            OptimalTemperature = 18.0,
                            PhotoUrl = "decor_41.jpg",
                            ShelfLifeDays = 365,
                            ShopId = 2,
                            Variety = "Упаковка и Декор"
                        },
                        new
                        {
                            Id = 42,
                            Color = "Натуральный",
                            Name = "Крафт бумага",
                            OptimalTemperature = 18.0,
                            PhotoUrl = "decor_42.jpg",
                            ShelfLifeDays = 365,
                            ShopId = 1,
                            Variety = "Упаковка и Декор"
                        },
                        new
                        {
                            Id = 43,
                            Color = "Красный",
                            Name = "Атласная лента",
                            OptimalTemperature = 18.0,
                            PhotoUrl = "decor_43.jpg",
                            ShelfLifeDays = 365,
                            ShopId = 2,
                            Variety = "Упаковка и Декор"
                        },
                        new
                        {
                            Id = 44,
                            Color = "Пудровый",
                            Name = "Корейская сетка",
                            OptimalTemperature = 18.0,
                            PhotoUrl = "decor_44.jpg",
                            ShelfLifeDays = 365,
                            ShopId = 1,
                            Variety = "Упаковка и Декор"
                        },
                        new
                        {
                            Id = 45,
                            Color = "Золотой",
                            Name = "Шелковая бумага",
                            OptimalTemperature = 18.0,
                            PhotoUrl = "decor_45.jpg",
                            ShelfLifeDays = 365,
                            ShopId = 2,
                            Variety = "Упаковка и Декор"
                        },
                        new
                        {
                            Id = 46,
                            Color = "Белый",
                            Name = "Свадебный каркас",
                            OptimalTemperature = 18.0,
                            PhotoUrl = "decor_46.jpg",
                            ShelfLifeDays = 365,
                            ShopId = 1,
                            Variety = "Упаковка и Декор"
                        },
                        new
                        {
                            Id = 47,
                            Color = "Черный",
                            Name = "Коробка шляпная",
                            OptimalTemperature = 18.0,
                            PhotoUrl = "decor_47.jpg",
                            ShelfLifeDays = 365,
                            ShopId = 2,
                            Variety = "Упаковка и Декор"
                        },
                        new
                        {
                            Id = 48,
                            Color = "Тиффани",
                            Name = "Корзина плетеная",
                            OptimalTemperature = 18.0,
                            PhotoUrl = "decor_48.jpg",
                            ShelfLifeDays = 365,
                            ShopId = 1,
                            Variety = "Упаковка и Декор"
                        },
                        new
                        {
                            Id = 49,
                            Color = "Бордовый",
                            Name = "Деревянный топпер",
                            OptimalTemperature = 18.0,
                            PhotoUrl = "decor_49.jpg",
                            ShelfLifeDays = 365,
                            ShopId = 2,
                            Variety = "Упаковка и Декор"
                        },
                        new
                        {
                            Id = 50,
                            Color = "Акварельный",
                            Name = "Открытка мини",
                            OptimalTemperature = 18.0,
                            PhotoUrl = "decor_50.jpg",
                            ShelfLifeDays = 365,
                            ShopId = 1,
                            Variety = "Упаковка и Декор"
                        });
                });

            modelBuilder.Entity("Albiflora.API.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FlowerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("RecommendedDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<decimal>("WasteProbability")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("WholesalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FlowerId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2778),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2779),
                            FlowerId = 1,
                            PurchasePrice = 217m,
                            Quantity = 28,
                            RecommendedDiscount = 0m,
                            SalePrice = 434m,
                            ShopId = 2,
                            WasteProbability = 0.18m,
                            WholesalePrice = 369m
                        },
                        new
                        {
                            Id = 2,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2787),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 24, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2787),
                            FlowerId = 2,
                            PurchasePrice = 178m,
                            Quantity = 94,
                            RecommendedDiscount = 0m,
                            SalePrice = 356m,
                            ShopId = 1,
                            WasteProbability = 0.08m,
                            WholesalePrice = 303m
                        },
                        new
                        {
                            Id = 3,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2790),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 24, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2790),
                            FlowerId = 3,
                            PurchasePrice = 145m,
                            Quantity = 69,
                            RecommendedDiscount = 0m,
                            SalePrice = 290m,
                            ShopId = 2,
                            WasteProbability = 0.10m,
                            WholesalePrice = 246m
                        },
                        new
                        {
                            Id = 4,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2793),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2793),
                            FlowerId = 4,
                            PurchasePrice = 88m,
                            Quantity = 89,
                            RecommendedDiscount = 0m,
                            SalePrice = 176m,
                            ShopId = 1,
                            WasteProbability = 0.18m,
                            WholesalePrice = 150m
                        },
                        new
                        {
                            Id = 5,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2795),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2796),
                            FlowerId = 5,
                            PurchasePrice = 86m,
                            Quantity = 87,
                            RecommendedDiscount = 0m,
                            SalePrice = 258m,
                            ShopId = 2,
                            WasteProbability = 0.08m,
                            WholesalePrice = 219m
                        },
                        new
                        {
                            Id = 6,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2825),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 25, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2826),
                            FlowerId = 6,
                            PurchasePrice = 195m,
                            Quantity = 15,
                            RecommendedDiscount = 0m,
                            SalePrice = 585m,
                            ShopId = 1,
                            WasteProbability = 0.10m,
                            WholesalePrice = 497m
                        },
                        new
                        {
                            Id = 7,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2828),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2828),
                            FlowerId = 7,
                            PurchasePrice = 87m,
                            Quantity = 20,
                            RecommendedDiscount = 0m,
                            SalePrice = 174m,
                            ShopId = 2,
                            WasteProbability = 0.06m,
                            WholesalePrice = 148m
                        },
                        new
                        {
                            Id = 8,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2830),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 24, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2830),
                            FlowerId = 8,
                            PurchasePrice = 243m,
                            Quantity = 83,
                            RecommendedDiscount = 0m,
                            SalePrice = 486m,
                            ShopId = 1,
                            WasteProbability = 0.13m,
                            WholesalePrice = 413m
                        },
                        new
                        {
                            Id = 9,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2833),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2833),
                            FlowerId = 9,
                            PurchasePrice = 62m,
                            Quantity = 89,
                            RecommendedDiscount = 0m,
                            SalePrice = 124m,
                            ShopId = 2,
                            WasteProbability = 0.09m,
                            WholesalePrice = 105m
                        },
                        new
                        {
                            Id = 10,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2836),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2836),
                            FlowerId = 10,
                            PurchasePrice = 116m,
                            Quantity = 90,
                            RecommendedDiscount = 0m,
                            SalePrice = 232m,
                            ShopId = 1,
                            WasteProbability = 0.20m,
                            WholesalePrice = 197m
                        },
                        new
                        {
                            Id = 11,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2838),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2839),
                            FlowerId = 11,
                            PurchasePrice = 159m,
                            Quantity = 67,
                            RecommendedDiscount = 0m,
                            SalePrice = 477m,
                            ShopId = 2,
                            WasteProbability = 0.00m,
                            WholesalePrice = 405m
                        },
                        new
                        {
                            Id = 12,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2840),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 23, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2841),
                            FlowerId = 12,
                            PurchasePrice = 65m,
                            Quantity = 18,
                            RecommendedDiscount = 0m,
                            SalePrice = 195m,
                            ShopId = 1,
                            WasteProbability = 0.09m,
                            WholesalePrice = 166m
                        },
                        new
                        {
                            Id = 13,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2843),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 25, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2843),
                            FlowerId = 13,
                            PurchasePrice = 204m,
                            Quantity = 54,
                            RecommendedDiscount = 0m,
                            SalePrice = 408m,
                            ShopId = 2,
                            WasteProbability = 0.13m,
                            WholesalePrice = 347m
                        },
                        new
                        {
                            Id = 14,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2845),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2845),
                            FlowerId = 14,
                            PurchasePrice = 150m,
                            Quantity = 110,
                            RecommendedDiscount = 0m,
                            SalePrice = 300m,
                            ShopId = 1,
                            WasteProbability = 0.22m,
                            WholesalePrice = 255m
                        },
                        new
                        {
                            Id = 15,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2847),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 23, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2848),
                            FlowerId = 15,
                            PurchasePrice = 289m,
                            Quantity = 89,
                            RecommendedDiscount = 0m,
                            SalePrice = 578m,
                            ShopId = 2,
                            WasteProbability = 0.08m,
                            WholesalePrice = 491m
                        },
                        new
                        {
                            Id = 16,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2849),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 24, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2850),
                            FlowerId = 16,
                            PurchasePrice = 244m,
                            Quantity = 29,
                            RecommendedDiscount = 0m,
                            SalePrice = 488m,
                            ShopId = 1,
                            WasteProbability = 0.25m,
                            WholesalePrice = 415m
                        },
                        new
                        {
                            Id = 17,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2851),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 26, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2852),
                            FlowerId = 17,
                            PurchasePrice = 241m,
                            Quantity = 90,
                            RecommendedDiscount = 0m,
                            SalePrice = 723m,
                            ShopId = 2,
                            WasteProbability = 0.16m,
                            WholesalePrice = 615m
                        },
                        new
                        {
                            Id = 18,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2854),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2854),
                            FlowerId = 18,
                            PurchasePrice = 56m,
                            Quantity = 112,
                            RecommendedDiscount = 0m,
                            SalePrice = 112m,
                            ShopId = 1,
                            WasteProbability = 0.01m,
                            WholesalePrice = 95m
                        },
                        new
                        {
                            Id = 19,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2856),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2857),
                            FlowerId = 19,
                            PurchasePrice = 104m,
                            Quantity = 59,
                            RecommendedDiscount = 0m,
                            SalePrice = 312m,
                            ShopId = 2,
                            WasteProbability = 0.03m,
                            WholesalePrice = 265m
                        },
                        new
                        {
                            Id = 20,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2859),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2859),
                            FlowerId = 20,
                            PurchasePrice = 130m,
                            Quantity = 93,
                            RecommendedDiscount = 0m,
                            SalePrice = 260m,
                            ShopId = 1,
                            WasteProbability = 0.21m,
                            WholesalePrice = 221m
                        },
                        new
                        {
                            Id = 21,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2861),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 24, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2861),
                            FlowerId = 21,
                            PurchasePrice = 273m,
                            Quantity = 112,
                            RecommendedDiscount = 0m,
                            SalePrice = 546m,
                            ShopId = 2,
                            WasteProbability = 0.16m,
                            WholesalePrice = 464m
                        },
                        new
                        {
                            Id = 22,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2863),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2863),
                            FlowerId = 22,
                            PurchasePrice = 206m,
                            Quantity = 46,
                            RecommendedDiscount = 0m,
                            SalePrice = 412m,
                            ShopId = 1,
                            WasteProbability = 0.23m,
                            WholesalePrice = 350m
                        },
                        new
                        {
                            Id = 23,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2865),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2865),
                            FlowerId = 23,
                            PurchasePrice = 296m,
                            Quantity = 29,
                            RecommendedDiscount = 0m,
                            SalePrice = 888m,
                            ShopId = 2,
                            WasteProbability = 0.14m,
                            WholesalePrice = 755m
                        },
                        new
                        {
                            Id = 24,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2867),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 26, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2868),
                            FlowerId = 24,
                            PurchasePrice = 189m,
                            Quantity = 27,
                            RecommendedDiscount = 0m,
                            SalePrice = 567m,
                            ShopId = 1,
                            WasteProbability = 0.11m,
                            WholesalePrice = 482m
                        },
                        new
                        {
                            Id = 25,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2869),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 25, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2870),
                            FlowerId = 25,
                            PurchasePrice = 137m,
                            Quantity = 63,
                            RecommendedDiscount = 0m,
                            SalePrice = 411m,
                            ShopId = 2,
                            WasteProbability = 0.03m,
                            WholesalePrice = 349m
                        },
                        new
                        {
                            Id = 26,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2871),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 23, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2872),
                            FlowerId = 26,
                            PurchasePrice = 76m,
                            Quantity = 34,
                            RecommendedDiscount = 0m,
                            SalePrice = 152m,
                            ShopId = 1,
                            WasteProbability = 0.15m,
                            WholesalePrice = 129m
                        },
                        new
                        {
                            Id = 27,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2873),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2874),
                            FlowerId = 27,
                            PurchasePrice = 150m,
                            Quantity = 110,
                            RecommendedDiscount = 0m,
                            SalePrice = 300m,
                            ShopId = 2,
                            WasteProbability = 0.08m,
                            WholesalePrice = 255m
                        },
                        new
                        {
                            Id = 28,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2875),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2876),
                            FlowerId = 28,
                            PurchasePrice = 185m,
                            Quantity = 113,
                            RecommendedDiscount = 0m,
                            SalePrice = 555m,
                            ShopId = 1,
                            WasteProbability = 0.08m,
                            WholesalePrice = 472m
                        },
                        new
                        {
                            Id = 29,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2878),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2878),
                            FlowerId = 29,
                            PurchasePrice = 181m,
                            Quantity = 40,
                            RecommendedDiscount = 0m,
                            SalePrice = 543m,
                            ShopId = 2,
                            WasteProbability = 0.07m,
                            WholesalePrice = 462m
                        },
                        new
                        {
                            Id = 30,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2880),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 25, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2880),
                            FlowerId = 30,
                            PurchasePrice = 107m,
                            Quantity = 82,
                            RecommendedDiscount = 0m,
                            SalePrice = 321m,
                            ShopId = 1,
                            WasteProbability = 0.22m,
                            WholesalePrice = 273m
                        },
                        new
                        {
                            Id = 31,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2882),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 26, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2882),
                            FlowerId = 31,
                            PurchasePrice = 244m,
                            Quantity = 114,
                            RecommendedDiscount = 0m,
                            SalePrice = 732m,
                            ShopId = 2,
                            WasteProbability = 0.04m,
                            WholesalePrice = 622m
                        },
                        new
                        {
                            Id = 32,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2884),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2884),
                            FlowerId = 32,
                            PurchasePrice = 196m,
                            Quantity = 81,
                            RecommendedDiscount = 0m,
                            SalePrice = 392m,
                            ShopId = 1,
                            WasteProbability = 0.20m,
                            WholesalePrice = 333m
                        },
                        new
                        {
                            Id = 33,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2886),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 25, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2886),
                            FlowerId = 33,
                            PurchasePrice = 136m,
                            Quantity = 90,
                            RecommendedDiscount = 0m,
                            SalePrice = 408m,
                            ShopId = 2,
                            WasteProbability = 0.15m,
                            WholesalePrice = 347m
                        },
                        new
                        {
                            Id = 34,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2889),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2889),
                            FlowerId = 34,
                            PurchasePrice = 99m,
                            Quantity = 20,
                            RecommendedDiscount = 0m,
                            SalePrice = 297m,
                            ShopId = 1,
                            WasteProbability = 0.04m,
                            WholesalePrice = 252m
                        },
                        new
                        {
                            Id = 35,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2891),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 23, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2891),
                            FlowerId = 35,
                            PurchasePrice = 122m,
                            Quantity = 107,
                            RecommendedDiscount = 0m,
                            SalePrice = 244m,
                            ShopId = 2,
                            WasteProbability = 0.19m,
                            WholesalePrice = 207m
                        },
                        new
                        {
                            Id = 36,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2893),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2893),
                            FlowerId = 36,
                            PurchasePrice = 215m,
                            Quantity = 52,
                            RecommendedDiscount = 0m,
                            SalePrice = 645m,
                            ShopId = 1,
                            WasteProbability = 0.23m,
                            WholesalePrice = 548m
                        },
                        new
                        {
                            Id = 37,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2895),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 23, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2896),
                            FlowerId = 37,
                            PurchasePrice = 198m,
                            Quantity = 55,
                            RecommendedDiscount = 0m,
                            SalePrice = 594m,
                            ShopId = 2,
                            WasteProbability = 0.22m,
                            WholesalePrice = 505m
                        },
                        new
                        {
                            Id = 38,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2897),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2898),
                            FlowerId = 38,
                            PurchasePrice = 128m,
                            Quantity = 107,
                            RecommendedDiscount = 0m,
                            SalePrice = 384m,
                            ShopId = 1,
                            WasteProbability = 0.15m,
                            WholesalePrice = 326m
                        },
                        new
                        {
                            Id = 39,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2899),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 26, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2900),
                            FlowerId = 39,
                            PurchasePrice = 54m,
                            Quantity = 58,
                            RecommendedDiscount = 0m,
                            SalePrice = 162m,
                            ShopId = 2,
                            WasteProbability = 0.07m,
                            WholesalePrice = 138m
                        },
                        new
                        {
                            Id = 40,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2901),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2902),
                            FlowerId = 40,
                            PurchasePrice = 285m,
                            Quantity = 18,
                            RecommendedDiscount = 0m,
                            SalePrice = 855m,
                            ShopId = 1,
                            WasteProbability = 0.17m,
                            WholesalePrice = 727m
                        },
                        new
                        {
                            Id = 41,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2903),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 24, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2904),
                            FlowerId = 41,
                            PurchasePrice = 180m,
                            Quantity = 51,
                            RecommendedDiscount = 0m,
                            SalePrice = 360m,
                            ShopId = 2,
                            WasteProbability = 0.15m,
                            WholesalePrice = 306m
                        },
                        new
                        {
                            Id = 42,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2906),
                            DiscountPercent = 0m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2906),
                            FlowerId = 42,
                            PurchasePrice = 130m,
                            Quantity = 25,
                            RecommendedDiscount = 0m,
                            SalePrice = 390m,
                            ShopId = 1,
                            WasteProbability = 0.24m,
                            WholesalePrice = 332m
                        },
                        new
                        {
                            Id = 43,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2908),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2908),
                            FlowerId = 43,
                            PurchasePrice = 137m,
                            Quantity = 75,
                            RecommendedDiscount = 0m,
                            SalePrice = 274m,
                            ShopId = 2,
                            WasteProbability = 0.16m,
                            WholesalePrice = 233m
                        },
                        new
                        {
                            Id = 44,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2910),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 24, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2910),
                            FlowerId = 44,
                            PurchasePrice = 77m,
                            Quantity = 33,
                            RecommendedDiscount = 0m,
                            SalePrice = 231m,
                            ShopId = 1,
                            WasteProbability = 0.16m,
                            WholesalePrice = 196m
                        },
                        new
                        {
                            Id = 45,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2912),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2912),
                            FlowerId = 45,
                            PurchasePrice = 265m,
                            Quantity = 79,
                            RecommendedDiscount = 0m,
                            SalePrice = 530m,
                            ShopId = 2,
                            WasteProbability = 0.20m,
                            WholesalePrice = 450m
                        },
                        new
                        {
                            Id = 46,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2914),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 26, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2914),
                            FlowerId = 46,
                            PurchasePrice = 188m,
                            Quantity = 85,
                            RecommendedDiscount = 0m,
                            SalePrice = 564m,
                            ShopId = 1,
                            WasteProbability = 0.17m,
                            WholesalePrice = 479m
                        },
                        new
                        {
                            Id = 47,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2916),
                            DiscountPercent = 10m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2916),
                            FlowerId = 47,
                            PurchasePrice = 106m,
                            Quantity = 71,
                            RecommendedDiscount = 0m,
                            SalePrice = 212m,
                            ShopId = 2,
                            WasteProbability = 0.15m,
                            WholesalePrice = 180m
                        },
                        new
                        {
                            Id = 48,
                            ArrivalDate = new DateTime(2026, 5, 17, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2918),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 21, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2918),
                            FlowerId = 48,
                            PurchasePrice = 237m,
                            Quantity = 118,
                            RecommendedDiscount = 0m,
                            SalePrice = 474m,
                            ShopId = 1,
                            WasteProbability = 0.10m,
                            WholesalePrice = 403m
                        },
                        new
                        {
                            Id = 49,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2920),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 26, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2921),
                            FlowerId = 49,
                            PurchasePrice = 155m,
                            Quantity = 74,
                            RecommendedDiscount = 0m,
                            SalePrice = 310m,
                            ShopId = 2,
                            WasteProbability = 0.12m,
                            WholesalePrice = 264m
                        },
                        new
                        {
                            Id = 50,
                            ArrivalDate = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2948),
                            DiscountPercent = 5m,
                            ExpiryDate = new DateTime(2026, 5, 22, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2948),
                            FlowerId = 50,
                            PurchasePrice = 127m,
                            Quantity = 90,
                            RecommendedDiscount = 0m,
                            SalePrice = 254m,
                            ShopId = 1,
                            WasteProbability = 0.20m,
                            WholesalePrice = 216m
                        });
                });

            modelBuilder.Entity("Albiflora.API.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("ShopId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Albiflora.API.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOwned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubscriptionActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RentPaymentDate")
                        .HasColumnType("integer");

                    b.Property<decimal>("RentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TariffPlan")
                        .HasColumnType("integer");

                    b.Property<decimal>("UtilityBills")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseKey")
                        .IsUnique();

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "г. Ростов-на-Дону, ул. Большая Садовая, д. 45",
                            CreatedAt = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2352),
                            IsOwned = true,
                            IsSubscriptionActive = true,
                            LicenseKey = "MAIN-ROSTOV-2026",
                            Name = "Albiflora Главный Филиал",
                            RentPrice = 0m,
                            SubscriptionEndDate = new DateTime(2027, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2353),
                            TariffPlan = 2,
                            UtilityBills = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "г. Ростов-на-Дону, пр. Стачки, д. 102",
                            CreatedAt = new DateTime(2026, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2392),
                            IsOwned = false,
                            IsSubscriptionActive = true,
                            LicenseKey = "WEST-ROSTOV-2026",
                            Name = "Albiflora Западный",
                            RentPaymentDate = 5,
                            RentPrice = 45000m,
                            SubscriptionEndDate = new DateTime(2026, 6, 1, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2393),
                            TariffPlan = 1,
                            UtilityBills = 8000m
                        });
                });

            modelBuilder.Entity("Albiflora.API.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Albiflora.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSubscriptionActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ShopId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TariffPlan")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "director@albiflora.ru",
                            IsSubscriptionActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "admin",
                            SubscriptionEndDate = new DateTime(2027, 5, 18, 12, 7, 51, 255, DateTimeKind.Utc).AddTicks(2443),
                            TariffPlan = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "anna2@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria3@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "elena4@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 5,
                            Email = "olga5@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 6,
                            Email = "daria6@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 7,
                            Email = "irina7@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 8,
                            Email = "kate8@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 9,
                            Email = "natalia9@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 10,
                            Email = "julia10@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 11,
                            Email = "sveta11@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 12,
                            Email = "anna12@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 13,
                            Email = "maria13@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 14,
                            Email = "elena14@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 15,
                            Email = "olga15@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 16,
                            Email = "daria16@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 17,
                            Email = "irina17@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 18,
                            Email = "kate18@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 19,
                            Email = "natalia19@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 20,
                            Email = "julia20@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 21,
                            Email = "sveta21@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 22,
                            Email = "anna22@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 23,
                            Email = "maria23@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 24,
                            Email = "elena24@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 25,
                            Email = "olga25@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 26,
                            Email = "daria26@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 27,
                            Email = "irina27@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 28,
                            Email = "kate28@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 29,
                            Email = "natalia29@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 30,
                            Email = "julia30@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 31,
                            Email = "sveta31@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 32,
                            Email = "anna32@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 33,
                            Email = "maria33@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 34,
                            Email = "elena34@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 35,
                            Email = "olga35@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 36,
                            Email = "daria36@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 37,
                            Email = "irina37@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 38,
                            Email = "kate38@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 39,
                            Email = "natalia39@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 40,
                            Email = "julia40@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 41,
                            Email = "sveta41@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 42,
                            Email = "anna42@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 43,
                            Email = "maria43@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 44,
                            Email = "elena44@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 45,
                            Email = "olga45@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 46,
                            Email = "daria46@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 47,
                            Email = "irina47@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 48,
                            Email = "kate48@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 49,
                            Email = "natalia49@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 50,
                            Email = "julia50@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "Florist",
                            ShopId = 1,
                            TariffPlan = 0
                        },
                        new
                        {
                            Id = 51,
                            Email = "sveta51@albiflora.ru",
                            IsSubscriptionActive = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEFA1...",
                            Role = "user",
                            ShopId = 2,
                            TariffPlan = 0
                        });
                });

            modelBuilder.Entity("Albiflora.API.Entities.Flower", b =>
                {
                    b.HasOne("Albiflora.API.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Albiflora.API.Entities.InventoryItem", b =>
                {
                    b.HasOne("Albiflora.API.Entities.Flower", "Flower")
                        .WithMany()
                        .HasForeignKey("FlowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flower");
                });

            modelBuilder.Entity("Albiflora.API.Entities.Sale", b =>
                {
                    b.HasOne("Albiflora.API.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId");

                    b.HasOne("Albiflora.API.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Albiflora.API.Entities.User", b =>
                {
                    b.HasOne("Albiflora.API.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId");

                    b.Navigation("Shop");
                });
#pragma warning restore 612, 618
        }
    }
}
